dist: xenial
language: python
python:
  - "3.7"
env:
# command to install dependencies, requirements.txt should NOT include numpy
before_install:
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -q
  - sudo apt-get install gdal-bin libgdal-dev python3-gdal -y
  - gdal-config --cflags
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
install:
  - pip install -r requirements.txt 
  - pip install gdal==`gdal-config --version`
# command to run tests
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd):/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages
  - echo $PYTHONPATH
script:
  - cd shetland
  - python3 -m pytest  

notifications:
  email: never
